### ISSUE TITLE
Testen der Schnittstelle

### ISSUE THREAD

**Issue by dominikstraessle** [Aaronmacaron/MultiSweeper#11]
# Testen der Schnittstelle

**Arbeitsaufwand geschätzt:**

**Comment by Aaronmacaron** [comment]
Wir haben gemerkt, dass diese Issue nicht wirklich umsetztbar ist, da man die Schnittstelle nicht wirklich testen kann. Die Schnittstelle ist im Grunde genommen das Interface und ein Interface kann man schlecht testen.
