### ISSUE TITLE
View-Logik implementieren

### ISSUE THREAD

**Issue by Aaronmacaron** [Aaronmacaron/MultiSweeper#12]
Es soll alle Logik die zu den Views gehört und unabhängig von den anderen Projektteilen ist, implementiert werden. Dazu gehören zum Beispiel diese Sachen:

- Controller erstellen
- Validierung hinzufügen
- Methoden-Stubs für Buttons usw. erstellen

**Geschätzter Aufwand:** 2h

**Comment by Aaronmacaron** [comment]
Partiell mit diesen commits erledigt: 
https://github.com/Aaronmacaron/MultiSweeper/commit/474b94f0eda2d1b9243c60359aa5febe60c63c59

Zeitaufwand: 0.5h

**Comment by mtte** [comment]
Partiell mit folgenden commits erledigt:
https://github.com/Aaronmacaron/MultiSweeper/commit/13d2a6fe07390f43af1159191e73ba57990cfa9a
https://github.com/Aaronmacaron/MultiSweeper/commit/8fb2edd683079ff1bb8be98d216d06ac9fadbd7b
https://github.com/Aaronmacaron/MultiSweeper/commit/8a5c6725357b613dc200464356702762c2cef126

Zeitaufwand: 0.5h

**Comment by dominikstraessle** [comment]
Partiell erledigt mit folgenden commits: 504d8de, 86e1401, 54eca03, 9ee4af5, 903fc0c, 748faf0, b092c6c
Zeitaufwand: 1.5h

**Comment by Aaronmacaron** [comment]
Nach dem ersten Sprint sind erst diese beiden Punkte erfüllt:

-  Controller erstellen
-  Methoden-Stubs für Buttons usw. erstellen

Die fehlenden Punkte werden im zweiten Sprint ausgeführt.

Der Zeitaufwand für den ersten Sprint für diese Issue war: 2.5h

**Comment by mtte** [comment]
Einige Anpassungen an der FinishedView:
4a25b39f6620b7c8be2dc4fd8a0f30393d619ad0
219504e8165fc3d238b1e38a93ab515b256953b0

Die View ist somit vorerst fertig. Ausserdem ist keine Validierung bei dieser View notwendig.

Zeitaufwand: 0.2h

**Comment by dominikstraessle** [comment]
Die Validierung auf den restlichen Views wurde mit folgenden Commits erledigt:
34672360145cde418e3677dfd2ee66b4cb1337b2
37de08e91e5e22f8ffa8e53b93fe1b371e9137e3

Dieses Issue kann somit beendet werden.

Zeitaufwand: 1h

**Comment by dominikstraessle** [comment]
Zeitaufwand für den zweiten Sprint: 0.2h
Zeitaufwand für den dritten Sprint: 1.2h

---
**Zeitaufwand gesamt: 3.9h**

**Comment by dominikstraessle** [comment]
ConfigurationView wurde nachgebessert mit folgendem Commit:
34b07f3aa499199c9d531947ae06a4e293ff829c

Zeitaufwand: 0.2 h
