### ISSUE TITLE
Verbindung von Conection API - Game Logik

### ISSUE THREAD

**Issue by mtte** [Aaronmacaron/MultiSweeper#18]
Die Spiellogik soll nun an die Connection API angebunden werden. Das heisst das neue Actions definiert werden müssen (Server zu Client) und die Action Handler (Client zu Server) entsprechend hinzugefügt werden, damit der Spielablauf vollendet ist.

Geschätzter Zeitaufwand: 5h

**Comment by mtte** [comment]
Funktion uf Spiel beizutreten hinzugefügt:
f111c6289a107265dd1c1b62a7973fe642450573
4800c9d078cb8331c626ccade0972276669a8f54

Zeitaufwand: 0.75h

**Comment by mtte** [comment]
Fuunktion um Spiel beizutreten erweitert: e930d4e632b8391c8f0f2a99f83c6b117c439bde

Zeitaufwand: 0.25h

**Comment by Aaronmacaron** [comment]
Erledigt von allen Mitglieder.
Insgesamter Zeitaufwand: 10h
