### ISSUE TITLE
Notificators implementieren

### ISSUE THREAD

**Issue by Aaronmacaron** [Aaronmacaron/MultiSweeper#21]
Es müssen alle Methoden die von den Notificator Interfaces definiert werden implementiert werden.

**Geschätzter Aufwand:** 4h

**Comment by dominikstraessle** [comment]
Die Notificators wurden erstellt.

c325456749f64726b24841825fb81aa46b011ae9

Zeitaufwand: 0.4h

**Comment by dominikstraessle** [comment]
Notificators wurden grösstenteils implementiert:

ee94b06e5025fa47bc145230c78c7a93ae83f0bb
67c06ee01413733d820d5753669809b8f2811c6a
252f71af2749da07030aa700c4037d1ea8c0c8df
b58c08fd0627232ec68c504743cf5bf71d6221e1
4782487efee69e8bbc0dd7ed203ca01880eb402b

Zeitaufwand: 0.4h

**Comment by Aaronmacaron** [comment]
Erledigt.

Zeitaufwand: 1h
