### ISSUE TITLE
ViewModel Logik implementieren

### ISSUE THREAD

**Issue by Aaronmacaron** [Aaronmacaron/MultiSweeper#22]
Es muss in jedem ViewModel die komplette Logik implementiert werden, welche auf die Messages des Servers reagiert und auch Messages an den Server sendet. Zudem müssen in den ViewModels alle Views immer korrekt upgedated und angezeigt werden.

**Geschätzter Aufwand:** 4h

**Comment by dominikstraessle** [comment]
Die Notificators wurden implementiert, allerdings noch mit leeren Methodenbodys.
Zudem wurden die Typen der Properties geändert.

3fa6f212609365958be916ee23b2269d06d26f9f

Zeitaufwand: 0.5h

**Comment by dominikstraessle** [comment]
Ein Spielfeld Prototyp wurde erstellt mit folgenden commits:
93cb2194b172625165d9c326b23f335d2a581da0
d7b72b965e00360cd61c1fd1cca2ed9c173f0816
63924abbd9bad5d37c7899edc108c5e4f54b78c8
5b2c6ceffb180fecc23ca839d61ac85155fbe2ff
d57fc54097489f596083d6149578409206db28aa
65edc48c69dddd00dd697e54560ea3b88a1aae33
f27474bdda567f618048854a6d02f20c8ed7df42
e79dfb218c475f7dc83ebb37a9fbd9d127638502
6659bda548db3955430933fcd412933f139b7fc1

Zeitaufwand: 4h

**Comment by mtte** [comment]
MultiSweeperView hinzugefügt, welche View, ViewModel und Notificator beninhaltet.
653f0e77fe9d7c8fd40a2c3753e173060c2aa508

Zeitaufwand: 0.75h

**Comment by dominikstraessle** [comment]
Viewmodels und Views wurden nachgebesert:

1452d1446673e72b7cc094763a8ced5908c084a1
dfaad4a7c11b7df3dcfcfb7ddeb3d14cdab20a11
ab9b97361fa09e6ec3229158db5eeb6445f4ec1b
db60b0d1ed14ed9d6ea5d005b377a156085053dd
d06487b1a64c36b55b16d965f09ce89010a763ed
7ca77d8935c670130f0ca76f75b66c248f31ca0f

Zeitaufwand: 1h

**Comment by dominikstraessle** [comment]
Kleine Korrekturen:

ec8e475460e91f04a08dffa81926c6e8f9c93788

Zeitaufwand: 0.1h

**Comment by Aaronmacaron** [comment]
Erledigt: 2h
