### ISSUE TITLE
Gradle tasks erweitern

### ISSUE THREAD

**Issue by mtte** [Aaronmacaron/MultiSweeper#25]
Die funktionalität von Gradle soll angepasst und entsprechend konfiguriert werden.
Dabei soll es möglcih sein, die Argumente für das Java-Programm mitzugeben.
Ausserdem soll das erstellen der Jar's funktionieren.

Geschätzter Zeitaufwand: 1h

**Comment by mtte** [comment]
### Die Argumente können nun Java übergeben werden.

Bsp -> Um den Server mit Gradle zu starten:
`gradle run :server:run -PappArgs="['port','anzahlGames']"`
Hier wird mit -P der Parameter appArgs gesetzt. Als Wert wird ein Array definiert, welches die Argumente beinhaltet.

**Commits**: 
ccc2fa6bbc4f78fa0d9076a60e857745c681492b
36758081bc16d6b7bb269fe9f71f16e3fd7a53de

**Zeitaufwand**: 0.5h

**Comment by Aaronmacaron** [comment]
Erledigt
Zeitaufwand: 1h
