### ISSUE TITLE
Verbesserungen

### ISSUE THREAD

**Issue by dominikstraessle** [Aaronmacaron/MultiSweeper#26]
Im Verlauf der letzten Sprints haben wir verschiedene kleine Fehler oder Unklarheiten entdeckt, welche behoben werden müssen, bevor wir normal weiterfahren können.

* Admin-Logik auf dem Client
* GameId-Logik auf dem Client
* Fenstergrösse der Game-View
* Bilder auf dem Client cachen
* Probleme mit dem Port auf dem Client
* Falsch delegierte Methoden auf dem Client
    * Die Methodennamen in den Viewmodels ändern

**Comment by Aaronmacaron** [comment]
Bilder auf dem Client cachen erledigt mit Commit: https://github.com/Aaronmacaron/MultiSweeper/commit/9c67437f6ae5aa92fd4d1e1608c4bc3a76b1583c

Zeitaufwand: 0.5h

**Comment by Aaronmacaron** [comment]
Probleme mit dem Port auf dem Client erledigt mit Commit: https://github.com/Aaronmacaron/MultiSweeper/commit/7fe03172f63596768646569cf9a945d649599e09

Zeitaufwand: 1h

**Comment by Aaronmacaron** [comment]
Fenstergrösse der GameView erledigt mit diesem Commit: https://github.com/Aaronmacaron/MultiSweeper/commit/0dfa0460fad8dbf980ffd965c2308b70c8e2cf1f

Zeitaufwand: 0.25h

**Comment by dominikstraessle** [comment]
Admin-Logik auf dem Client & GameId-Logik auf dem Client:

Hatte probleme mit git, daher ein kleines durcheinander...

8736b31aa353e1d0d3a14e41b72eef6d0a3e2ee0

Zeitaufwand: 0.4h

**Comment by mtte** [comment]
Connection API wurde angepasst zur einfacheren Benutzung: 22226426886e258c94019d24440ecd686038c229

Zeitaufwand: 0.5h

**Comment by dominikstraessle** [comment]
Erledigt.

Zeitaufwand Sprint 4: 2.65h
