### ISSUE TITLE
Views designen

### ISSUE THREAD

**Issue by Aaronmacaron** [Aaronmacaron/MultiSweeper#6]
Es sollen alle Views der Applikation designt und mit als FXML implementiert werden.

**Aufwand geschätzt:** 4h

**Comment by Aaronmacaron** [comment]
Partiell erledigt mit diesem commit: https://github.com/Aaronmacaron/MultiSweeper/commit/5fe0f80edc296ab0e743d02b6e6a8d289152b2c3
Zeitaufwand: 0.75h

**Comment by mtte** [comment]
Partiell erledigt mir diesem commit: https://github.com/Aaronmacaron/MultiSweeper/commit/676e4124ad6eed84f4ed5102eaa6fd8d774d6d3f
Zeitaufwand: 0.75h

**Comment by dominikstraessle** [comment]
Partiel erledigt mit diesen commits: https://github.com/Aaronmacaron/MultiSweeper/commit/504d8de1e15f100b73639a9ad2403f0cd9fe6fa9, https://github.com/Aaronmacaron/MultiSweeper/commit/86e14013335f810b3d8431310c148db5f2d06df5, https://github.com/Aaronmacaron/MultiSweeper/commit/54eca0345ea4b8d5d887ab75238d9a30c60bcb5f, https://github.com/Aaronmacaron/MultiSweeper/commit/9ee4af59dadb63b2122280303bfb37b0b9a14d15, https://github.com/Aaronmacaron/MultiSweeper/commit/903fc0c8d82e62491b39cc2201df5a419ecc9a9f,  https://github.com/Aaronmacaron/MultiSweeper/commit/748faf0c792b4214a99359baad46f6c90f344d5b, https://github.com/Aaronmacaron/MultiSweeper/commit/b092c6c6e22e850d25a32f1fc3bd9c4b41035cc3
Zeitaufwand: 2h

**Comment by mtte** [comment]
Alle Views sind fertig designed. Schlussendlicher Zeitaufwand: 3.5h
